import pandas as pd

test = pd.read_csv('../data/test.csv')
sub_47 = pd.read_csv('../submission_files/submission_47.csv')['Expected']
sub_48 = pd.read_csv('../submission_files/submission_48.csv')['Expected']
sub_45 = pd.read_csv('../submission_files/submission_45.csv')['Expected']
sub_xgb_50 = pd.read_csv('../submission_files/submission_xgb_50.csv')['Expected']
sub_xgb_51 = pd.read_csv('../submission_files/submission_xgb_51.csv')['Expected']
sub_xgb_52 = pd.read_csv('../submission_files/submission_xgb_52.csv')['Expected']
sub_xgb_53 = pd.read_csv('../submission_files/submission_xgb_53.csv')['Expected']
sub_xgb_54 = pd.read_csv('../submission_files/submission_xgb_54.csv')['Expected']
sub_xgb_55 = pd.read_csv('../submission_files/submission_xgb_55.csv')['Expected']
sub_xgb_58 = pd.read_csv('../submission_files/submission_xgb_58.csv')['Expected']
sub_xgb_59 = pd.read_csv('../submission_files/submission_xgb_59.csv')['Expected']
sub_xgb_60 = pd.read_csv('../submission_files/submission_xgb_60.csv')['Expected']
sub_xgb_61 = pd.read_csv('../submission_files/submission_xgb_61.csv')['Expected']
sub_xgb_62 = pd.read_csv('../submission_files/submission_xgb_62.csv')['Expected']
sub_xgb_63 = pd.read_csv('../submission_files/submission_xgb_63.csv')['Expected']
sub_xgb_64 = pd.read_csv('../submission_files/submission_xgb_64.csv')['Expected']
sub_xgb_65 = pd.read_csv('../submission_files/submission_xgb_65.csv')['Expected']
sub_xgb_67 = pd.read_csv('../submission_files/submission_xgb_67.csv')['Expected']
sub_xgb_68 = pd.read_csv('../submission_files/submission_xgb_68.csv')['Expected']
sub_xgb_69 = pd.read_csv('../submission_files/submission_xgb_69.csv')['Expected']
sub_xgb_72 = pd.read_csv('../submission_files/submission_xgb_72.csv')['Expected']
sub_xgb_75 = pd.read_csv('../submission_files/submission_xgb_75.csv')['Expected']
sub_xgb_76 = pd.read_csv('../submission_files/submission_xgb_76.csv')['Expected']
sub_xgb_77 = pd.read_csv('../submission_files/submission_xgb_77.csv')['Expected']
sub_xgb_78 = pd.read_csv('../submission_files/submission_xgb_78.csv')['Expected']
sub_xgb_79 = pd.read_csv('../submission_files/submission_xgb_79.csv')['Expected']
sub_xgb_80 = pd.read_csv('../submission_files/submission_xgb_80.csv')['Expected']
sub_xgb_83 = pd.read_csv('../submission_files/submission_xgb_83.csv')['Expected']
sub_xgb_84 = pd.read_csv('../submission_files/submission_xgb_84.csv')['Expected']
sub_xgb_85 = pd.read_csv('../submission_files/submission_xgb_85.csv')['Expected']
sub_xgb_86 = pd.read_csv('../submission_files/submission_xgb_86.csv')['Expected']
sub_xgb_88 = pd.read_csv('../submission_files/submission_xgb_88.csv')['Expected']
sub_xgb_89 = pd.read_csv('../submission_files/submission_xgb_89.csv')['Expected']
sub_xgb_90 = pd.read_csv('../submission_files/submission_xgb_90.csv')['Expected']
sub_xgb_91 = pd.read_csv('../submission_files/submission_xgb_91.csv')['Expected']
sub_xgb_92 = pd.read_csv('../submission_files/submission_xgb_92.csv')['Expected']
sub_xgb_93 = pd.read_csv('../submission_files/submission_xgb_93.csv')['Expected']
sub_xgb_94 = pd.read_csv('../submission_files/submission_xgb_94.csv')['Expected']
sub_xgb_95 = pd.read_csv('../submission_files/submission_xgb_95.csv')['Expected']
sub_xgb_96 = pd.read_csv('../submission_files/submission_xgb_96.csv')['Expected']
sub_xgb_97 = pd.read_csv('../submission_files/submission_xgb_97.csv')['Expected']
sub_xgb_98 = pd.read_csv('../submission_files/submission_xgb_98.csv')['Expected']
sub_xgb_99 = pd.read_csv('../submission_files/submission_xgb_99.csv')['Expected']
sub_xgb_100 = pd.read_csv('../submission_files/submission_xgb_100.csv')['Expected']
sub_xgb_101 = pd.read_csv('../submission_files/submission_xgb_101.csv')['Expected']
sub_xgb_102 = pd.read_csv('../submission_files/submission_xgb_102.csv')['Expected']
sub_xgb_103 = pd.read_csv('../submission_files/submission_xgb_103.csv')['Expected']
sub_xgb_104 = pd.read_csv('../submission_files/submission_xgb_104.csv')['Expected']
sub_xgb_105 = pd.read_csv('../submission_files/submission_xgb_105.csv')['Expected']
sub_xgb_106 = pd.read_csv('../submission_files/submission_xgb_106.csv')['Expected']
sub_xgb_107 = pd.read_csv('../submission_files/submission_xgb_107.csv')['Expected']
sub_xgb_108 = pd.read_csv('../submission_files/submission_xgb_108.csv')['Expected']
sub_xgb_110 = pd.read_csv('../submission_files/submission_xgb_110.csv')['Expected']
sub_xgb_111 = pd.read_csv('../submission_files/submission_xgb_111.csv')['Expected']
sub_xgb_113 = pd.read_csv('../submission_files/submission_xgb_113.csv')['Expected']
sub_xgb_115 = pd.read_csv('../submission_files/submission_xgb_115.csv')['Expected']
sub_xgb_116 = pd.read_csv('../submission_files/submission_xgb_116.csv')['Expected']
sub_xgb_117 = pd.read_csv('../submission_files/submission_xgb_117.csv')['Expected']
sub_xgb_118 = pd.read_csv('../submission_files/submission_xgb_118.csv')['Expected']
sub_xgb_121 = pd.read_csv('../submission_files/submission_xgb_121.csv')['Expected']
sub_xgb_122 = pd.read_csv('../submission_files/submission_xgb_122.csv')['Expected']
sub_xgb_123 = pd.read_csv('../submission_files/submission_xgb_123.csv')['Expected']
sub_xgb_124 = pd.read_csv('../submission_files/submission_xgb_124.csv')['Expected']
sub_26 = pd.read_csv('../submission_files/submission_26.csv')['Expected']
sub_28 = pd.read_csv('../submission_files/submission_28.csv')['Expected']
sub_29 = pd.read_csv('../submission_files/submission_29.csv')['Expected']
sub_36 = pd.read_csv('../submission_files/submission_36.csv')['Expected']
sub_43 = pd.read_csv('../submission_files/submission_43.csv')['Expected']

subs = pd.concat([sub_29, sub_xgb_50, sub_xgb_51, sub_xgb_52, sub_xgb_53, sub_xgb_54, sub_xgb_65, sub_xgb_78,  sub_xgb_79, sub_xgb_80, sub_xgb_83,
                  sub_xgb_84, sub_xgb_85, sub_xgb_86, sub_xgb_88, sub_xgb_89, sub_xgb_90, sub_xgb_91, sub_xgb_92,
                  sub_xgb_93, sub_xgb_94, sub_xgb_95, sub_xgb_96, sub_xgb_97, sub_xgb_98, sub_xgb_99, sub_xgb_100,
                  sub_xgb_101, sub_xgb_102, sub_xgb_103, sub_xgb_104, sub_xgb_105, sub_xgb_106, sub_xgb_107,
                  sub_xgb_108, sub_xgb_110, sub_xgb_111, sub_xgb_113, sub_xgb_115, sub_xgb_116, sub_xgb_117,
                  sub_xgb_118, sub_xgb_121, sub_xgb_122, sub_xgb_123, sub_xgb_124], axis=1)
subs_2 = pd.concat([sub_29, sub_xgb_100, sub_xgb_103], axis=1)
subs.columns = ['29', '50', '51', '52', '53', '54', '65', '78', '79', '80', '83', '84', '85', '86', '88', '89', '90',
                '91', '92', '93', '94', '95', '96', '97', '98', '99', '100', '101', '102', '103',
                '104', '105', '106', '107', '108', '110', '111', '113', '115', '116', '117', '118', '121', '122', '123', '124']
subs_2.columns = ['29', '100', '103']
sub = pd.concat([test, subs], axis=1)
# sub['mean'] = sub.mean(axis=1)
# sub['47'] = sub['47'] / sub['mean']
# sub['48'] = sub['48'] / sub['mean']
# sub['45'] = sub['45'] / sub['mean']
# sub['xgb_54'] = sub['xgb_54'] / sub['mean']
# sub['xgb_55'] = sub['xgb_55'] / sub['mean']
# sub['26'] = sub['26'] / sub['mean']
# sub['28'] = sub['28'] / sub['mean']
# sub['29'] = sub['29'] / sub['mean']
# sub['36'] = sub['36'] / sub['mean']
# sub['43'] = sub['43'] / sub['mean']

pass
